name: Docker

on:
  workflow_call: 
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: josealceu # user on DockerHub
        password: ${{secrets.PASSWORD}}

    - name: Set Docker Build
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
          context: .
          file: ./Dockerfile

          push: true 
        
          tags: josealceu/go-ci:${{github.ref_name}}


