name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
    # Username used to log against the Docker registry
        username: josealceu
    # Password or personal access token used to log against the Docker registry
        password: ${{secrets.PASSWORD}}
    - name: Docker build and push
      # You may pin to the exact commit or the version.
      # uses: cloudposse/github-action-docker-build-push@e2e648a687d73800bb0cfaa098ec8bf60f0bd4ac
      uses: cloudposse/github-action-docker-build-push@1.9.0
      with:
 
        context: .
        file: ./Dockerfile
        push: true
        tags: josealceu/go_ci:latest
